name: Organize LeetHub Files

on:
  push:
    branches:
      - main  

jobs:
  organize:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Run organize script
        run: node organize.js

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Organized files automatically" || echo "No changes to commit"
          git push
