name: Organize LeetHub Files

on:
  push:
    branches:
      - main  

jobs:
  organize:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # 👈 مهم عشان يقدر يـpush

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Run organize script
        run: node organize.js

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add .
          git diff --cached --quiet || git commit -m "Organized files automatically"
          git push origin HEAD:main